// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8mQpB4ddOO63cdEG9tMH6qT-zIw2MQC4',
    appId: '1:665184414778:web:59bcdd52be268199035903',
    messagingSenderId: '665184414778',
    projectId: 'telemedicineapp-9bc1b',
    authDomain: 'telemedicineapp-9bc1b.firebaseapp.com',
    storageBucket: 'telemedicineapp-9bc1b.firebasestorage.app',
    measurementId: 'G-S7Z4E1QYP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwqWi8apsKdB0ofLl0po-q4pSy_fn8jsw',
    appId: '1:665184414778:android:7e07b68d49e312c1035903',
    messagingSenderId: '665184414778',
    projectId: 'telemedicineapp-9bc1b',
    storageBucket: 'telemedicineapp-9bc1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuL9HFQm3uLgNgVNHm4SyyEaMblLx0EfA',
    appId: '1:665184414778:ios:b478dfd2a136e9b5035903',
    messagingSenderId: '665184414778',
    projectId: 'telemedicineapp-9bc1b',
    storageBucket: 'telemedicineapp-9bc1b.firebasestorage.app',
    iosBundleId: 'com.example.telemedicineFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuL9HFQm3uLgNgVNHm4SyyEaMblLx0EfA',
    appId: '1:665184414778:ios:b478dfd2a136e9b5035903',
    messagingSenderId: '665184414778',
    projectId: 'telemedicineapp-9bc1b',
    storageBucket: 'telemedicineapp-9bc1b.firebasestorage.app',
    iosBundleId: 'com.example.telemedicineFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8mQpB4ddOO63cdEG9tMH6qT-zIw2MQC4',
    appId: '1:665184414778:web:f283f866786ed4ac035903',
    messagingSenderId: '665184414778',
    projectId: 'telemedicineapp-9bc1b',
    authDomain: 'telemedicineapp-9bc1b.firebaseapp.com',
    storageBucket: 'telemedicineapp-9bc1b.firebasestorage.app',
    measurementId: 'G-ZR6HYCPMZQ',
  );
}
